### ISSUE TITLE
怎么实时编译

### ISSUE THREAD

**Issue by a15218378694** [lyfeyaj/ewa#10]
运行dist报错
![运行报错2](https://user-images.githubusercontent.com/29919045/56370750-655b2300-622e-11e9-9548-28a5441d05ed.png)
![运行项目报错](https://user-images.githubusercontent.com/29919045/56370753-65f3b980-622e-11e9-8130-5518ab1fe509.png)

**Comment by oimken** [comment]
没有设置appid, 生成个测试的appid就可以

**Comment by lyfeyaj** [comment]
实时编译的启动命令是在项目根目录下面，运行 `ewa start`
