### ISSUE TITLE
ewa build打包运行异常，ewa start正常

### ISSUE THREAD

**Issue by xiaogouxo** [lyfeyaj/ewa#12]
环境描述：mac os 10.13.5 
node:v8.11.2
配置:开启es6转es5,开启使用 npm 模块
调试基础库:2.6.5
如题，调试环境一切ok，正式build的时候一些组件无法正常显示和执行，但是并没有异常抛出。不知道是不是压缩混淆的时候出了问题，但是还是非常希望有混淆功能对代码提供了一层保护。目前使用ewa start打包的代码提交审核，再次感谢作者提供这么好的工具！

**Comment by xiaogouxo** [comment]
没有使用ewa build打包正式环境，开启webpack混淆压缩功能，实现了代码混淆，具体步骤：
npm i -D uglifyjs-webpack-plugin
修改ewa.config.js
```
'use strict';
const UglifyJsPlugin = require('uglifyjs-webpack-plugin');
...
  // webpack 插件
  plugins: [
    new UglifyJsPlugin()
  ],
```
希望留给后来人

**Comment by lyfeyaj** [comment]
`ewa build` 会自动混淆并压缩所有代码。

可以尝试关闭微信开发者工具的 `开启es6转es5` 配置后，再试试

**Comment by lyfeyaj** [comment]
@xiaogouxo  关闭微信开发者工具的`开启es6转es5` 选项之后，可以解决问题么？

**Comment by xiaogouxo** [comment]
@lyfeyaj  关闭 `开启es6转es5` 还是一样，部分组件功能异常，没有异常抛出。目前使用npm start加插件解决压缩混淆的需求，感谢！
