### ISSUE TITLE
初始化项目

### ISSUE THREAD

**Issue by LeeYongDae** [lyfeyaj/ewa#22]
安装完了ewa-cli之后，ewa new <xxxxx>之后报`无法将“ewa”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确`请问这个怎么解决。

**Comment by lyfeyaj** [comment]
ewa-cli 是通过 `npm i -g ewa-cli` 的方式安装到全局的么？

**Comment by LeeYongDae** [comment]
是的呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lyfeyaj"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月8日(星期五) 晚上8:40
收件人:&nbsp;"lyfeyaj/ewa"<ewa@noreply.github.com&gt;;
抄送:&nbsp;"胡杨"<1345029964@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [lyfeyaj/ewa] 初始化项目 (#22)





 
ewa-cli 是通过 npm i -g ewa-cli 的方式安装到全局的么？

**Comment by lyfeyaj** [comment]
建议看下 node 在 windows 上的环境配置是否有问题

**Comment by LeeYongDae** [comment]
好的，回头我看一下。谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lyfeyaj"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月9日(星期六) 晚上7:13
收件人:&nbsp;"lyfeyaj/ewa"<ewa@noreply.github.com&gt;;
抄送:&nbsp;"胡杨"<1345029964@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [lyfeyaj/ewa] 初始化项目 (#22)





 
建议看下 node 在 windows 上的环境配置是否有问题
