### ISSUE TITLE
scss/less文件没有编译

### ISSUE THREAD

**Issue by sandmanman** [lyfeyaj/ewa#28]
按照文档安装。发现项目中的SCSS/LESS文件没有编译。请问需要哪里再配置吗？

**Comment by lyfeyaj** [comment]
![image](https://user-images.githubusercontent.com/1445568/86534816-1ae6c480-bf0e-11ea-8db0-f826d01774b1.png)

ewa.config.js 文件的配置项里面可以指定 css 的解析器 。另外可以尝试重装下命令行工具 `npm i -g ewa-cli@latest`

如果问题依然没解决，请提供下有问题的 sample
