### ISSUE TITLE
用import 会复制被import的文件，有没有办法采用小程序原生的import，不编译

### ISSUE THREAD

**Issue by Tim1023** [lyfeyaj/ewa#3]
用import 会复制被import的文件，有没有办法采用小程序原生的import，不编译

**Comment by lyfeyaj** [comment]
小程序原生并不提供 ES6 的 `import`，而是 commonjs 的 `require`

**Comment by Tim1023** [comment]
小程序原生 应该是支持es6 import的，
在处理 js 和 wxss 里想实现 不处理转换成 require 有什么办法吗
