### ISSUE TITLE
页面里不支持直接 编译 .scss 文件 吗

### ISSUE THREAD

**Issue by itboos** [lyfeyaj/ewa#36]
你好~， 想问下

项目配置里设置的是使用 ```sass ``` 预处理器,

页面结构大致如下：
```
├── pages                    小程序页面目录
│   │   ├── index
│   │   │   ├── index.js
│   │   │   ├── index.wxml
│   │   │   └── index.scss
```

执行 ```build``` 操作

查看 dist 目录， 发现 并没有 ``` index.wxss``` 文件

是不会自动编译 ```scss``` 文件的吗？

但是，发现 ```index.wxss``` 文件里可以直接使用 scss 语法， 也会参与编译， 

但如果就是想用 ```index.scss``` 文件的命名方式呢？ 是我的操作不对吗？

**Comment by clevok** [comment]
+1，不过我是 .sass, 我也不行，切换less也不行

**Comment by lyfeyaj** [comment]
建议直接在 wxss 中使用 scss 的语法，原因是目前编译 scss 的时候，如果有公用的 scss 文件，里面的代码会被复制到每一个文件里面，会显著的增大小程序包的大小，而使用 wxss 的时候会利用小程序支持的 `@import` 功能，避免 scss 会被直接合并的问题

后面会增加下 scss 直接编译为 wxss 的支持（仅当页面或组件没有 wxss 而有 scss 的时候）

**Comment by lyfeyaj** [comment]
已通过 #37 支持，升级 ewa-cli 为最新即可使用

`npm i -g ewa-cli@0.4.18`
