### ISSUE TITLE
copy-webpack-plugin 插件没有兼容 Windows？

### ISSUE THREAD

**Issue by icai** [lyfeyaj/ewa#46]
Windows 下图片无法复制

**Comment by lyfeyaj** [comment]
手头目前没有 Windows 电脑，没办法测试，感觉上不大可能不支持 Windows。有什么明确的报错么？

**Comment by lyfeyaj** [comment]
如果 Windows 的支持有问题，通常情况下是路径问题导致的，可以检查下看看

**Comment by icai** [comment]
@lyfeyaj  mac 下面是正常的， windows 没有输出报错。该是 copy-webpack-plugin 组件的 分隔符 问题

https://github.com/lyfeyaj/ewa/blob/4e1ebeb2406b1edac58f722ae71e477d4407c48c/packages/webpack/lib/config.js#L94

---

https://github.com/webpack-contrib/copy-webpack-plugin#for-windows

**Comment by icai** [comment]
@lyfeyaj  改成这样子，Windows 正常了

```js
      from: path.posix.join(
        path.resolve(ROOT, "src").replace(/\\/g, "/"),
        "**", `*.{${options.copyFileTypes.join(',')}}`
      )
```

**Comment by lyfeyaj** [comment]
新版本已修复。

![image](https://user-images.githubusercontent.com/1445568/115333329-130dbd80-a1cc-11eb-917f-5bedb295c480.png)
