### ISSUE TITLE
添加一个引入 vant-weapp 的 demo可以吗？

### ISSUE THREAD

**Issue by icai** [lyfeyaj/ewa#47]
如题。

**Comment by lyfeyaj** [comment]
vant-weapp 有给出使用方法，可以参考下：

![image](https://user-images.githubusercontent.com/1445568/116684984-3e6e8480-a9e4-11eb-82c3-fcf88a5feb3a.png)

**Comment by icai** [comment]
这样子报错……

```
// 通过 npm 安装
// app.json
"usingComponents": {
  "van-button": "@vant/weapp/button/index"
}
```

https://youzan.github.io/vant-weapp/#/quickstart

**Comment by lyfeyaj** [comment]
可以将 <https://github.com/youzan/vant-weapp/tree/dev/dist> 目录下的内容整个拷贝到 你的项目中，然后按照实际的组件路径来引用，例如：

1. 将 vant-weapp 的组件代码拷贝至如下项目目录： `src/vant-weapp` 中
2. 在组件中引用的路径为 `"./vant-weapp/target_component_name"`

**Comment by icai** [comment]
@lyfeyaj 我的同事应该跟你讲过， $emit 方法会跟 vant-weapp 冲突的。同时 vant-weapp 的组件代码拷贝至如下项目目录： `src/vant-weapp` 中,  也会导致生成 sourcemap 过大，真机调试失败……

**Comment by lyfeyaj** [comment]
sourceMap 过大的问题，可以通过在 `ewa.config.js` 中修改 webpack 配置来关闭 sourceMap，方法如下:

![image](https://user-images.githubusercontent.com/1445568/119101844-0343fc00-ba4c-11eb-8ce4-0375dfdf5e5f.png)

另外最新版本的 ewa 中 createStore 插件允许为注入的方法自定义名称，可以解决 $emit 命名冲突的问题

```
 - ewa-cli@1.2.0
 - ewa@1.2.0
 - ewa-webpack@1.2.0
```
