### ISSUE TITLE
您好，感谢你分享的那么好的脚手架！问下关于Promise和async await的问题

### ISSUE THREAD

**Issue by oimken** [lyfeyaj/ewa#9]
您好，感谢你分享的那么好的脚手架！
刚刚才试用了下，比重型的框架好多了，清爽快捷还优雅！
特别对于新手来说，微信小程序都那么多坑了，
还要踩更多框架的坑太不爽了。
十分感谢有ewa！

缺点是文档虽然漂亮但实在太简单了，对新手很难，
碰到了几个问题想请教下，如果能在文档上加上多一点点的例子就更好了。

#### 在文档里有关Promise和async await的例子

貌似只能在 onload 这些生命周期事件里使用？不能全局使用么？
如果过可以的话，能不能请您给些例子，方便使用。

```
微信接口 Promise 化
const { wx } = require('ewa');

Page({
  async onLoad() {
    let { data } = await wx.request({ url: 'http://your_api_endpoint' });
  }
})
```

#### 关于  ewa 通过 ewa.config.js 来支持个性化配置
能不能给些关于webpack config的例子呢
```
  // 嫌不够灵活？直接修改 webpack 配置
  webpack: function(config) {
    return config;
  }
```

**Comment by lyfeyaj** [comment]
感谢信赖和试用 😄 

> 在文档里有关Promise和async await的例子

`async await` 可以在全局放心大胆的使用

示例:

```javascript
const { wx } = require('ewa');

async function fetchArticles() {
  let res = await wx.request({ url: 'http://your_api_endpoint/articles' });
  return res.data;
}

Page({
  async onLoad() {
    let articles = await fetchArticles();
  }
})
```

> 关于 ewa 通过 ewa.config.js 来支持个性化配置

`wenpack` 个性化配置这块儿，后续我会再完善下文档，增加一些示例

**Comment by oimken** [comment]
谢谢您那么快回复，我刚才翻看了下源码

尝试这样使用但失败了，log无输出
不知道哪里有问题，小白问题请谅。    

```javascript
const {wx, promisify} = require('ewa');

promisify(wx.checkSession)().then(() => {
      console.log('无token，重新登录');
    }).catch(e => {
      console.log(e);
    });
```

**Comment by lyfeyaj** [comment]
从 `ewa` 引用出来的wx，里面的接口都被Promise化了
所以正确的用法是：

```javascript
const { wx } = require('ewa');

wx.checkSession().then(() => {
  console.log('无token，重新登录');
}).catch(e => {
  console.log(e);
});
```

**Comment by lyfeyaj** [comment]
参见示例：

代码：

![image](https://user-images.githubusercontent.com/1445568/56404775-2ca56300-629b-11e9-9ba1-324cfd86ef51.png)

运行效果：

![image](https://user-images.githubusercontent.com/1445568/56404792-45157d80-629b-11e9-8349-f1376d0bd4a5.png)
